FROM java:8-jre
MAINTAINER TP tp <tfy824@qq.com>

ADD ./jar/tp-upms-service.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx1000m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=tp-upms-service", "-Dpinpoint.applicationName=TP-UPMS-SERVICE", "-jar", "/app/tp-upms-service.jar"]

